# Remember to npm install -g react-sctipts, npm install -g eslint, npm install

SHELL := /bin/bash

build-static:
	cd src && npm run build

build-static-dev:
	cd src && npm run build-dev

install:
	npm install

all: install build-static
